---

- name: "Playbook: Install K3S"
  hosts: "{{ args_host }}"
  gather_facts: false

  vars_files:
    - /etc/ansible/inventory/vars.yml

  tasks:
    - ansible.builtin.include_role:
        name: alex.container.installk3s
    - ansible.builtin.include_role:
        name: alex.container.installhelm
    - ansible.builtin.include_role:
        name: alex.container.installoras
    - ansible.builtin.include_role:
        name: alex.container.installregistry

   
